import { Priority, type Task, type User, type DayColumn } from "./types"

export const USERS: User[] = [
  { id: "1", name: "Alex", avatar: "https://picsum.photos/32/32?random=1" },
  { id: "2", name: "Sarah", avatar: "https://picsum.photos/32/32?random=2" },
  { id: "3", name: "Mike", avatar: "https://picsum.photos/32/32?random=3" },
  { id: "4", name: "Lisa", avatar: "https://picsum.photos/32/32?random=4" },
]

export const TASKS: Task[] = [
  {
    id: "t1",
    title: "Database Migration",
    dateRange: "Mon 24 - Tue 25",
    priority: Priority.HIGH,
    progress: 75,
    assignees: [USERS[0], USERS[1]],
    row: 0,
    startDay: 0,
    span: 2,
    color: "#3b82f6",
  },
  {
    id: "t2",
    title: "Marketing Campaign",
    dateRange: "Wed 26 - Sat 29",
    priority: Priority.HIGH,
    progress: 40,
    assignees: [USERS[2], USERS[3]],
    row: 0,
    startDay: 2,
    span: 4,
    color: "#f97316",
  },
  {
    id: "t3",
    title: "Product Design",
    dateRange: "Mon 24 - Tue 25",
    priority: Priority.LOW,
    progress: 100,
    assignees: [USERS[1]],
    row: 1,
    startDay: 0,
    span: 2,
    color: "#22c55e",
  },
  {
    id: "t4",
    title: "Frontend Optimization",
    dateRange: "Wed 26 - Sat 29",
    priority: Priority.HIGH,
    progress: 10,
    assignees: [USERS[0], USERS[2], USERS[3]],
    row: 1,
    startDay: 2,
    span: 4,
    color: "#ec4899",
  },
  {
    id: "t5",
    title: "Code Review",
    dateRange: "Mon 24 - Fri 28",
    priority: Priority.LOW,
    progress: 90,
    assignees: [USERS[0], USERS[1], USERS[2], USERS[3]],
    row: 2,
    startDay: 0,
    span: 5,
    color: "#a855f7",
  },
  {
    id: "t6",
    title: "Quality Assurance",
    dateRange: "Tue 25 - Wed 26",
    priority: Priority.MEDIUM,
    progress: 50,
    assignees: [USERS[1]],
    row: 3,
    startDay: 1,
    span: 2,
    color: "#eab308",
  },
  {
    id: "t7",
    title: "Documentation Update",
    dateRange: "Fri 28 - Sun 30",
    priority: Priority.HIGH,
    progress: 20,
    assignees: [USERS[2], USERS[3]],
    row: 3,
    startDay: 4,
    span: 3,
    color: "#f43f5e",
  },
]

export const DAYS: DayColumn[] = [
  { name: "Mon", date: 24, isToday: false },
  { name: "Tue", date: 25, isToday: false },
  { name: "Wed", date: 26, isToday: false },
  { name: "Thu", date: 27, isToday: false },
  { name: "Fri", date: 28, isToday: false },
  { name: "Sat", date: 29, isToday: false },
  { name: "Sun", date: 30, isToday: false },
]
